// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/rate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// below numbers are orders, not values. used to convert to binary
type RateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRequest) Reset() {
	*x = RateRequest{}
	mi := &file_proto_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRequest) ProtoMessage() {}

func (x *RateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRequest.ProtoReflect.Descriptor instead.
func (*RateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_proto_rawDescGZIP(), []int{0}
}

func (x *RateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type RateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"` // double in Protobuf for float64 in Go
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_proto_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_proto_rawDescGZIP(), []int{1}
}

func (x *RateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RateResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RateResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type CryptoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoRequest) Reset() {
	*x = CryptoRequest{}
	mi := &file_proto_rate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoRequest) ProtoMessage() {}

func (x *CryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoRequest.ProtoReflect.Descriptor instead.
func (*CryptoRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_proto_rawDescGZIP(), []int{2}
}

func (x *CryptoRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type CryptoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"` // usdt price
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // binance api or cache
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoResponse) Reset() {
	*x = CryptoResponse{}
	mi := &file_proto_rate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoResponse) ProtoMessage() {}

func (x *CryptoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoResponse.ProtoReflect.Descriptor instead.
func (*CryptoResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_proto_rawDescGZIP(), []int{3}
}

func (x *CryptoResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CryptoResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CryptoResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_proto_rate_proto protoreflect.FileDescriptor

const file_proto_rate_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rate.proto\x12\x05rates\"=\n" +
	"\vRateRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"j\n" +
	"\fRateResponse\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"'\n" +
	"\rCryptoRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"V\n" +
	"\x0eCryptoResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source2\x8f\x01\n" +
	"\x13ExchangeRateService\x12:\n" +
	"\x0fGetExchangeRate\x12\x12.rates.RateRequest\x1a\x13.rates.RateResponse\x12<\n" +
	"\rGetCryptoRate\x12\x14.rates.CryptoRequest\x1a\x15.rates.CryptoResponseB\x14Z\x12./internal/grpc/pbb\x06proto3"

var (
	file_proto_rate_proto_rawDescOnce sync.Once
	file_proto_rate_proto_rawDescData []byte
)

func file_proto_rate_proto_rawDescGZIP() []byte {
	file_proto_rate_proto_rawDescOnce.Do(func() {
		file_proto_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rate_proto_rawDesc), len(file_proto_rate_proto_rawDesc)))
	})
	return file_proto_rate_proto_rawDescData
}

var file_proto_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rate_proto_goTypes = []any{
	(*RateRequest)(nil),    // 0: rates.RateRequest
	(*RateResponse)(nil),   // 1: rates.RateResponse
	(*CryptoRequest)(nil),  // 2: rates.CryptoRequest
	(*CryptoResponse)(nil), // 3: rates.CryptoResponse
}
var file_proto_rate_proto_depIdxs = []int32{
	0, // 0: rates.ExchangeRateService.GetExchangeRate:input_type -> rates.RateRequest
	2, // 1: rates.ExchangeRateService.GetCryptoRate:input_type -> rates.CryptoRequest
	1, // 2: rates.ExchangeRateService.GetExchangeRate:output_type -> rates.RateResponse
	3, // 3: rates.ExchangeRateService.GetCryptoRate:output_type -> rates.CryptoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rate_proto_init() }
func file_proto_rate_proto_init() {
	if File_proto_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rate_proto_rawDesc), len(file_proto_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rate_proto_goTypes,
		DependencyIndexes: file_proto_rate_proto_depIdxs,
		MessageInfos:      file_proto_rate_proto_msgTypes,
	}.Build()
	File_proto_rate_proto = out.File
	file_proto_rate_proto_goTypes = nil
	file_proto_rate_proto_depIdxs = nil
}
